server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Usar resolver interno de Docker para evaluar 'api' en tiempo real
    resolver 127.0.0.11 valid=30s;

    # Proxy para conectar con FastAPI usando el dominio público de Dokploy
    location /api/ {
        set $upstream https://sports-api.perfil.plus;
        proxy_pass $upstream;
        proxy_set_header Host sports-api.perfil.plus;
        proxy_ssl_server_name on;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
